[2025-06-19T11:31:18.963+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T11:31:18.983+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T11:31:18.986+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T11:31:19.006+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 00:00:00+00:00
[2025-06-19T11:31:19.022+0000] {standard_task_runner.py:60} INFO - Started process 1067 to run task
[2025-06-19T11:31:19.029+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmps2c1iaoc']
[2025-06-19T11:31:19.031+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask validate_data
[2025-06-19T11:31:19.130+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T11:31:19.299+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T00:00:00+00:00'
[2025-06-19T11:31:19.302+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T11:31:19.319+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T000000, start_date=20250619T113118, end_date=20250619T113119
[2025-06-19T11:31:19.369+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:31:19.409+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:06:15.314+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T12:06:15.401+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T12:06:15.406+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:06:15.481+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 00:00:00+00:00
[2025-06-19T12:06:15.526+0000] {standard_task_runner.py:60} INFO - Started process 1592 to run task
[2025-06-19T12:06:15.546+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmpfif7p2gs']
[2025-06-19T12:06:15.558+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask validate_data
[2025-06-19T12:06:15.713+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T12:06:16.066+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T00:00:00+00:00'
[2025-06-19T12:06:16.073+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:06:16.096+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T000000, start_date=20250619T120615, end_date=20250619T120616
[2025-06-19T12:06:16.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:06:16.255+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:19:05.012+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T12:19:05.134+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [queued]>
[2025-06-19T12:19:05.136+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:19:05.348+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 00:00:00+00:00
[2025-06-19T12:19:05.409+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2025-06-19T12:19:05.470+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmpc_29rzur']
[2025-06-19T12:19:05.490+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask validate_data
[2025-06-19T12:19:05.897+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T00:00:00+00:00 [running]> on host b96384fab38e
[2025-06-19T12:19:06.671+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T00:00:00+00:00'
[2025-06-19T12:19:06.676+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:19:06.699+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T000000, start_date=20250619T121905, end_date=20250619T121906
[2025-06-19T12:19:06.798+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:19:06.973+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
