[2025-06-19T11:31:19.247+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T11:31:19.259+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T11:31:19.259+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T11:31:19.281+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 03:00:00+00:00
[2025-06-19T11:31:19.292+0000] {standard_task_runner.py:60} INFO - Started process 1068 to run task
[2025-06-19T11:31:19.305+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T03:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmp85tbw2fc']
[2025-06-19T11:31:19.307+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask validate_data
[2025-06-19T11:31:19.394+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T11:31:19.605+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T03:00:00+00:00'
[2025-06-19T11:31:19.609+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T11:31:19.684+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T030000, start_date=20250619T113119, end_date=20250619T113119
[2025-06-19T11:31:19.807+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T11:31:19.883+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:06:16.271+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T12:06:16.308+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T12:06:16.311+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:06:16.358+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 03:00:00+00:00
[2025-06-19T12:06:16.391+0000] {standard_task_runner.py:60} INFO - Started process 1593 to run task
[2025-06-19T12:06:16.396+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T03:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmp0sym8ria']
[2025-06-19T12:06:16.403+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask validate_data
[2025-06-19T12:06:16.718+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [running]> on host 77bf71b7bc3a
[2025-06-19T12:06:17.009+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T03:00:00+00:00'
[2025-06-19T12:06:17.016+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:06:17.061+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T030000, start_date=20250619T120616, end_date=20250619T120617
[2025-06-19T12:06:17.121+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:06:17.300+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T12:19:06.720+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T12:19:06.760+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [queued]>
[2025-06-19T12:19:06.760+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-06-19T12:19:06.824+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): validate_data> on 2025-06-19 03:00:00+00:00
[2025-06-19T12:19:06.852+0000] {standard_task_runner.py:60} INFO - Started process 145 to run task
[2025-06-19T12:19:06.863+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'week_3_weather_api_dag', 'validate_data', 'scheduled__2025-06-19T03:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/week_3_weather_api_dag.py', '--cfg-path', '/tmp/tmpcnqdhuvo']
[2025-06-19T12:19:06.875+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask validate_data
[2025-06-19T12:19:07.140+0000] {task_command.py:423} INFO - Running <TaskInstance: week_3_weather_api_dag.validate_data scheduled__2025-06-19T03:00:00+00:00 [running]> on host b96384fab38e
[2025-06-19T12:19:07.522+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='week_3_weather_api_dag' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-19T03:00:00+00:00'
[2025-06-19T12:19:07.528+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-19T12:19:07.598+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=week_3_weather_api_dag, task_id=validate_data, execution_date=20250619T030000, start_date=20250619T121906, end_date=20250619T121907
[2025-06-19T12:19:07.739+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-19T12:19:07.899+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
